### ISSUE TITLE
Docker FrontEnd 테스트 페이지 활성화

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/Docker-Study#9]
# Docker FrontEnd 팀장 테스트 페이지 활성화
## 개요
- Server 팀장이 Front 페이지 전용 서버(24시간 활성화 용)를 만들어 봄.

## 과정
- https://github.com/Biccon/biccon.github.io.git 에서 clone 하여 제작
- ### Dockerfile
  - #### Source Code
  ``` Dockerfile
    FROM nginx:latest  # nginx image 사용                                                                                                  
    MAINTAINER s5kywa1k3r # 제작자                                                                                                                                                                                                
    COPY ./biccon.github.io/ /home/front/ # Image에 clone한 Source Code들을 복사
  ```
  - #### 설명
    - nginx로 웹 서버를 돌려야 하는데 일단 제작되어져 있는 Source Code들을 nginx image에 복사하여 새로운 image를 제작

- ### docker-compose
  - #### Source Code
  ``` yml
  front_test:
      build: ./frontdocker # frontdocker 폴더 내의 Dockerfile을 이용하여
      image: front:test     # front:test Image 생성
      # volumes:              # 기존에는 host volume과 mount 하였으나 일단 COPY를 사용함
      #     - ./frontdocker/biccon.github.io:/home/front
      ports:                      # <Host IP or Domain>:30280 <-> container:80 연결
          - "30280:80"
      command:
          - /bin/bash
          - -c
          - |
              cp -r /home/front/* /usr/share/nginx/html/  # nginx html 폴더에 Source Code 복사
              nginx -g "daemon off;" # nginx image에 있던 CMD 실행
  ``` 

- ### 결론
  1. nginx image를 이용하여 front 페이지를 띄울 수 있는 컨테이너 제작 성공
  2. /usr/share/nginx/html 폴더에 front 팀에서 제작한 코드를 넣으면 실행됨
  3. front 관련 image의 CMD(command)는 nginx -g "daemon off;" 를 사용
  4. front 팀장님께서는 이 실행 방법이 맞는지 Feedback 주시면 감사하겠습니다.
